<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntime.DirectML" Version="1.24.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Etssd.Core\Etssd.Core.csproj" />
    <ProjectReference Include="..\Etssd.Bridge\Etssd.Bridge.csproj" />
  </ItemGroup>

</Project>
