<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Vortice.DXGI" Version="3.8.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Etssd.Core\Etssd.Core.csproj" />
    <ProjectReference Include="..\Etssd.Bridge\Etssd.Bridge.csproj" />
    <ProjectReference Include="..\Etssd.Inference\Etssd.Inference.csproj" />
  </ItemGroup>

</Project>
